### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by victorlin** [nextstrain/auspice#1874]
From @jameshadfield in https://github.com/nextstrain/auspice/pull/1863#discussion_r1802068783:

> if you see stuff that is clearly poorly implemented it's probably because it was just a poor implementation. Please add a FIXME comment in the code or just fix it. I'd prefer inconsistent code over consistently bad code.

## Tasks

- [ ] Pass props to reducer functions as an object ([ref](https://github.com/nextstrain/auspice/pull/1863#discussion_r1794400284))
- [ ] Simplify function definitions ([ref](https://github.com/nextstrain/auspice/pull/1373#discussion_r1794389062))
- [ ] Rename variables that use "display order" terminology ([ref](https://github.com/nextstrain/auspice/pull/1373#discussion_r1803959069))
    - I'll plan to do this as part of #1864
- [ ] Rename `tipCount` as `visibleTipCount` ([ref](https://github.com/nextstrain/auspice/pull/1373#discussion_r1807935508))
    - I'll plan to do this as part of #1864
