### ISSUE TITLE
Layouts

### ISSUE THREAD

**Issue by trvrb** [nextstrain/auspice#20]
Include multiple tree layout options.
- [x] Rooted tree
  - [x] as mutation count vs Y as layout (current default)
  - [x] as time vs Y as layout (timetree)
  - [x] as time vs Y as mutation count (Path-O-Gen plot)
  - [ ] as mutation count vs Y as antigenic distance
- [x] Unrooted tree
- [x] Radial tree

I think this is one dropdown with multiple layout options.

**Comment by rneher** [comment]
layouts and scales (time vs divergence) should live in `query.params`. need a way to update `xScale` `yScale`, which are in `tree.state.xScale` etc. Similarly functions that assign node location and branch geometry need to respond to changes in `query.params.layout`

**Comment by rneher** [comment]
Mutation count vs titers is a specific features, no need to be in epic
