### ISSUE TITLE
narrative to-do list

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#527]
### Dataset loading & URLs
- [ ] When pathname changes between paragraphs, the dataset needs to be swapped out (without a page refresh). The JSON(s) should be pre-fetched. (Not required for "release")
- [ ] Ensure twin-trees work. (Not required for "release")
- [ ] Sort out hosting (probably github / gists). Could be https://nextstrain.org/narratives/githubOrg/githubRepo (which would expect a `narrative.md` file in that directory) and/or https://nextstrain.org/narratives/githubOrg/githubRepo/fileName. Could also have https://nextstrain.org/narratives/fileName for ones hosted by us (perhaps on another S3 bucket).

### Aesthetics
- [ ] Double scroll bars sometimes
- [ ] Text differences between in-focus paragraphs / some way to convey what's in focus
- [ ] Image sizing
- [ ] Clearer authorship at the top.
- [ ] Intro to narrative concept at the top (before first paragraph)
- [ ] Some indication of how far through the narrative you are
- [ ] Info information above each paragraph to describe what state the app is in.

### Functionality
- [ ] Allow single image in app. (Not required for "release")
- [ ] Remove certain callbacks when in narrative mode (e.g. `on branch click`)
- [x] Genotype colorBy issues
- [x] Stream graph layout percentages
- [x] Stream graph updates
- [ ] non-linear scrolling, i.e. when threshold is reached the next paragraph scrolls into view & the app state changes.
- [ ] hand/finger icon at bottom of page indicating to scroll or click on icon (same result as scroll). 
- [ ] starting page (n=0) does not include the first paragraph, only author title etc

### State to put into URL
- [ ] Labels on tree.  (Not required for "release")
- [ ] Map co-ordinates.  (Not required for "release")
- [ ] Genome zoom bounds.  (Not required for "release")

### Other
- [ ] write docs

**Comment by jameshadfield** [comment]
Now in master. Additional points can be separate issues.
