### ISSUE TITLE
whitelabelling to-do list

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#680]
- [ ] improve, discuss & document sidebar theme interface
    - [ ] move `Select` to styled-components
- [ ] document component extension interface
    - [ ] Splash page interface
    - [ ] nav-bar interface
- [ ] discuss & document server interface / API
    - [ ] consider pseudo-static syntax, e.g. `domain/datasets/zika.json`, `.../available/staging.json`
    - [ ] available datasets structure
    - [ ] narratives structure
    - [ ] deliver datasets using scheme 2.0
    - [ ] hardcoded paths interface (gh-pages)
- [x] available datasets shouldn't use `source` -- this should all be done by the server. (`source` may be provided by the dataset itself to influence the sidebar)
- [x] client shouldn't use `_available`, but make a call for `charon/getAvailable`
- [ ] client should parse schema 2.0 JSONs
- [x] rename `server.js` -> `auspice.js` and use subcommands `build`, `view` etc
     - [x] `view` & `view --dev`
     - [x] move webpack configs into `build`
     - [x] `build` generates files (index.html, bundle etc) in appropriate directory
     - [x] `build --github-pages` uses `dist/` etc (not `/dist/`)
     - [x] `view --github-pages`
- [ ] handle auspice URLs starting with `local` by redirecting
- [x] documentation in `auspice/docs`
    - [x] compile to static site (gh-pages?)
- [x] nextstrain.org:
    - [x] remove community URL functionality
    - [x] improve server logic / readability
- [ ] auspice.us
    - [x] add community URLs
    - [ ] splash page
    - [ ] access docs (via cname docs.auspice.us -> github pages?)
    - [ ] enable narrative functionality
    - [ ] drag & drop should work after going back to the splash page
- [ ] github-pages (server-less)
     - [ ] allow starting in narrative mode
     - [ ] remove splash page from bundle
     - [ ] disable all pathname manipulation
- [x] favicon
- [x] page title
- [ ] ensure replaced components don't end up in the bundle *Not needed for release*

**Comment by eharkins** [comment]
@jameshadfield just flagging this but letting you close in case there are things you want to decompose into other issues still here.

**Comment by jameshadfield** [comment]
Closing as out of date
